version: '3'
services:
  test:
    image: svelte-squad/splash-dev
    container_name: splash-test
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    command: "npm run test"
volumes:
  node_modules:
  test-db-volume: